### GENERAL SETTINGS ###

# Site settings
title: Saurabh Kulkarni
description: "Masters Student at UCSD"
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "https://saurabhkulkarni2312.github.io/"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#757677" #"#F70031" 00b3fe 98afba
  primary_rgb: "117,118,119" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"
  
  
### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: linkedin
    url: https://www.linkedin.com/in/saurabhkulkarni2312
  - title: portfolium
    url: https://portfolium.com/saurabhkulkarni

    
# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines: 
    - San Diego,
    - CA, United States.
email: saurabhkulkarni2312@gmail.com
#tel: 


### GENERAL DATA FOR VARIOUS LOCATIONS ###
    
# Members information. Shown on About page.

    
# about: "Thanks for visiting. This site is under construction. Do reach me out on LinkedIn or through gmail"

# Testimonial content. Shown on Home and About page. 
#testimonial:
#    message: Masters Students in UCSD."
#    author: 
#    position: 